name: Deploy to Development
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          VITE_DEV_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_RAPID_API_KEY: ${{ secrets.VITE_RAPID_API_KEY }}
          VITE_RAPID_API_HOST: ${{ secrets.VITE_RAPID_API_HOST }}
          VITE_DEV_FIREBASE_API_KEY: ${{ secrets.VITE_DEV_FIREBASE_API_KEY }}
          VITE_DEV_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_DEV_FIREBASE_AUTH_DOMAIN }}
          VITE_DEV_FIREBASE_PROJECT_ID: ${{ secrets.VITE_DEV_FIREBASE_PROJECT_ID }}
          VITE_DEV_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_DEV_FIREBASE_STORAGE_BUCKET }}
          VITE_DEV_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_DEV_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_DEV_FIREBASE_APP_ID: ${{ secrets.VITE_DEV_FIREBASE_APP_ID }}
          VITE_DEV_FIREBASE_DATABASE_URL: ${{ secrets.VITE_DEV_FIREBASE_DATABASE_URL }}
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --only hosting:myclubs-dev --project myclubs-dev-769d7
        env:
          DEV_FIREBASE_TOKEN: ${{ secrets.DEV_FIREBASE_TOKEN }}
