name: Deploy to Development
on:
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Install Firebase Tools
      run: npm install -g firebase-tools
    - name: Deploy to Firebase
      run: firebase deploy --only hosting:myclubs-dev
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}